version: "3.8"

services:
  mysql-data-base:
    container_name: mysql-database
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: training
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: springboot-test
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-data-base
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: